### ISSUE TITLE
German umlaut not correct replaced...

### ISSUE THREAD

**Issue by Dexus** [pid/speakingurl#123]
i have "datenschurtzerklärung" as slug, but it will not be "datenschutzerklaerung" it gets "datenschutzerla_rung" with option `{lang:'de',seperator:'_'}`

Additional: Running on MacOS High Sierra and Linux Ubuntu 18.04 same problem

**Comment by kwiatkk1** [comment]
Hi, the reason is that you can represent ä in many ways in unicode string (`ä` or `a\u0308`). If you use latter, a combining character (https://www.fileformat.info/info/unicode/char/0308/index.htm), then transliteration breaks, as it process string char by char.

The solution is to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize before transliteration. See #126 that contains proposed solution.

**Comment by Dexus** [comment]
Thanks, that will help.

**Comment by Dexus** [comment]
BTW: https://github.com/walling/unorm would help for 0.10.x
