### ISSUE TITLE
Chinese and Japanese support

### ISSUE THREAD

**Issue by Gouthamve** [pid/speakingurl#61]
Support for Chinese and Japanese would be great!

https://github.com/reactioncommerce/reaction/issues/384

Thanks,
Goutham.

**Comment by pid** [comment]
Go with "limax". The goal for SpeakingURL was, that it's running in the browser, too. To implement chinese and japanese support I would actually use the same libs as limax. limax uses speakingurl as dependency, but don't know if this module works also in browser/client side. Check it out for your requirements. Because of lack of knowledge with chinese/japanese language I have no plans to implement it myself soon.
