### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by marbemac** [pid/speakingurl#98]
Great job with this library, we really appreciate it! I'd like to suggest that you all follow semantic versioning. It's a bit jarring to see the major version bumps all the time, and means our team has to review the changes to make sure nothing is breaking. The most recent releases are just adding new languages (and a bug fix). Would you be ok with doing minor 0.x.0 version bumps for new features, patch bumps 0.0.x for bug fixes, and reserving the major bumps for actual breaking changes? Would love to hear your thoughts!

**Comment by simi** [comment]
@marbemac as I was discussed by author, he's actually following sem. ver. Changes bumping major version are not backward compatible (aka you can get different result). I think that's right.

For example https://github.com/pid/speakingurl/commit/790931a63608fbbb3f789e447d7afcb62ebc9ab1 bumped major version also, because your output will differ before/after.

I think that's actually right usage of sem ver.

**Comment by marbemac** [comment]
Ah yeah I guess that makes sense. For some reason I didn't consider language additions as breaking, but I guess they could technically break usage since output will be different. Closing!
